[package]
name = "kmon"
version = "0.1.0"
authors = ["orhun <orhunparmaksiz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
tui = "0.8.0"
termion = "1.5.4"
failure = "0.1.6"
bytesize = "1.0.0"
unicode-width = "0.1.7"
enum-unitary = "0.4.1"
enum-iterator = "0.5.0"
