name: kmon
version: git
summary: Linux kernel manager and activity monitor
description: |
  kmon provides a text-based user interface for
  managing the Linux kernel modules and monitoring 
  the kernel activities.
base: core18
grade: stable
confinement: classic
parts:
  kmon:
    plugin: rust
    source: .
    build-packages:
      - libxcb1-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
    stage-packages:
      - libxcb1
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
apps:
  kmon:
    command: kmon